all:
	gcc -g -o gstreamer_camera_record main.c `pkg-config --cflags --libs gstreamer-1.0`
clean:
	rm -f gstreamer_camera_record
#https://gstreamer.freedesktop.org/documentation/installing/on-windows.html?gi-language=cs