PRESRC=examples
all:
	gcc -g -o abgr ${PRESRC}/abgr.c -lglut -lGLU -lGL -lm
	gcc -g -o halomagic ${PRESRC}/halomagic.c -lglut -lGLU -lGL -lm
	gcc -g -o evaltest ${PRESRC}/evaltest.c -lglut -lGLU -lGL -lm
clean:
	rm -f abgr halomagic evaltest