#export PKG_CONFIG_LIBDIR=/home/thuannt/x/FFmpeg/zffmpeg/pkgconfig:${PKG_CONFIG_LIBDIR}
INC_LIB_PATH=-I/usr/local/include -L/mingw64/bin/ -L/usr/local/bin/
INC_LIB_PATH+= -lavcodec -lavformat -lswscale -lavfilter -lavdevice -lavutil
INC_LIB_PATH+= 

all:
	gcc -g -o main main.c ${INC_LIB_PATH}
clean:
	rm -rf main

#export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:"/home/thuannt/x/FFmpeg/zffmpeg"
#git config --global user.name "Thuận Nguyễn-Thái"
#avcodec.lib;avformat.lib;swscale.lib;avfilter.lib;avdevice.lib;lavutil.lib



        liblzma-5.dll => /mingw64/bin/liblzma-5.dll (0x7ff88a7f0000)
        libiconv-2.dll => /mingw64/bin/libiconv-2.dll (0x7ff88a6d0000)
        libbz2-1.dll => /mingw64/bin/libbz2-1.dll (0x7ff88a6b0000)
        libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x7ff88a690000)
        zlib1.dll => /mingw64/bin/zlib1.dll (0x7ff88a660000)
        libx264-164.dll => /mingw64/bin/libx264-164.dll (0x7fff981c0000)
        libx265-215.dll => /mingw64/bin/libx265-215.dll (0x7fff984b0000)

        libopenal-1.dll => /mingw64/bin/libopenal-1.dll (0x7fff97930000)

        libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x7fff976d0000)

        libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x7ff802cc0000)
        libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x1ffd7400000)


